from cirq import *
images=Queue()
images.createQueue(15)
images.enqueue("q1.gif")
images.enqueue("q2.gif")
images.enqueue("q3.gif")
images.enqueue("q4.gif")
images.enqueue("q5.gif")
images.enqueue("q6.gif")
images.enqueue("q7.gif")
images.enqueue("q8.gif")
images.enqueue("q9.gif")
images.enqueue("q10.gif")
images.enqueue("q11.gif")
images.enqueue("q12.gif")
images.enqueue("q13.gif")
images.enqueue("q14.gif")
images.enqueue("q15.gif")
