from cirq import *
answers=Queue()
answers.createQueue(15)
answers.enqueue("christmas")
answers.enqueue("rainbow")
answers.enqueue("cardboard")
answers.enqueue("sharpener")
answers.enqueue("background")
answers.enqueue("facebook")
answers.enqueue("breakfast")
answers.enqueue("golf")
answers.enqueue("waterfall")
answers.enqueue("rotten")
answers.enqueue("toast")
answers.enqueue("tablespoon")
answers.enqueue("library")
answers.enqueue("blacksmith")
answers.enqueue("birthday")
